import { createBrowserRouter } from 'react-router-dom'

// Routes are automatically generated by Vite Plugin Remix Router
// and are based on the file system structure.
import { routes } from 'virtual:routes'

export const router = createBrowserRouter(routes)
